os: linux
dist: xenial
language: python
python:
  - "3.8"

script:
  - pip3 install -r requirements.txt > /dev/null
  - python3 scraper.py

notifications:
  email:
    on_success: never
    on_failure: always
